name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2' # نسخه Ruby مناسب Jekyll
        bundler-cache: true # کش کردن bundle برای سرعت

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll site
      run: |
        bundle exec jekyll build --future --destination _site

    - name: Upload built site as artifact
      uses: actions/upload-artifact@v3
      with:
        name: jekyll-site
        path: _site

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        commit_message: "Deploy Jekyll site via GitHub Actions"
